### ISSUE TITLE
'cz_conventional_commits_info.txt' file not included in package

### ISSUE THREAD

**Issue by ohing504** [Woile/commitizen#3]
Hello, Woile.

**Commitizen Version**: 0.9.5

**Problem**: `cz info` command not work.

```shell
$ cz info
Traceback (most recent call last):
  File "/Users/ohing/.virtualenvs/app-vktpxFKO/bin/cz", line 11, in <module>
    sys.exit(main())
  File "/Users/ohing/.virtualenvs/app-vktpxFKO/lib/python3.6/site-packages/commitizen/cli.py", line 127, in main
    args.func(args)
  File "/Users/ohing/.virtualenvs/app-vktpxFKO/lib/python3.6/site-packages/commitizen/__init__.py", line 75, in show_info
    _commiter.show_info()
  File "/Users/ohing/.virtualenvs/app-vktpxFKO/lib/python3.6/site-packages/commitizen/cz/cz_base.py", line 85, in show_info
    logger.info(self.info())
  File "/Users/ohing/.virtualenvs/app-vktpxFKO/lib/python3.6/site-packages/commitizen/cz/cz_conventional_commits.py", line 132, in info
    with open(filepath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ohing/.virtualenvs/app-vktpxFKO/lib/python3.6/site-packages/commitizen/cz/cz_conventional_commits_info.txt'
```

The `cz info` command not work, because the 'cz_conventional_commits_info.txt' file is not included in package.
I think, 'setup.py' need to be updated to including text files.

**Comment by Woile** [comment]
Thanks for the feedback, I'll take a look into it! Probably publish a new version with the fix

**Comment by Woile** [comment]
@ohing504 fixed, can you confirm please?

`pip install -U commitizen` should install `v0.9.6`

Sorry for the delay.
