### ISSUE TITLE
first run always fail

### ISSUE THREAD

**Issue by maxandersen** [Woile/commitizen#8]
ran `pip install`, ran `cz -h` to see help and you get:

```
cz -h                                                                                                      ✘ 1 semantic_release ✭ ✱ ◼
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 845, in items
    d.update(self._sections[section])
KeyError: 'commitizen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/max/code/home-assistant-cli/bin/cz", line 11, in <module>
    sys.exit(main())
  File "/Users/max/code/home-assistant-cli/lib/python3.7/site-packages/commitizen/cli.py", line 115, in main
    config = load_cfg()
  File "/Users/max/code/home-assistant-cli/lib/python3.7/site-packages/commitizen/cli.py", line 109, in load_cfg
    defaults.update(dict(config.items("commitizen")))
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 848, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'commitizen'
```

I would expect being able to run the tool to see its help before configuring it.

**Comment by Woile** [comment]
Yes, it should default to that. I'm gonna fix it. Thanks!

**Comment by Woile** [comment]
fixed! @maxandersen
